### YamlMime:ManagedReference
items:
- uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
  commentId: T:TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
  id: TalkAction.TalkSettings.EvaluationResult
  parent: TinyLife.Actions
  children: []
  langs:
  - csharp
  - vb
  name: TalkAction.TalkSettings.EvaluationResult
  nameWithType: TalkAction.TalkSettings.EvaluationResult
  fullName: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
  type: Delegate
  source:
    remote:
      path: TinyLife/Actions/TalkAction.cs
      branch: main
      repo: https://git.ellpeck.de/Ellpeck/TinyLife
    id: EvaluationResult
    path: ../TinyLife/Actions/TalkAction.cs
    startLine: 481
  assemblies:
  - Tiny Life
  namespace: TinyLife.Actions
  summary: A delegate that is used for <xref href="TinyLife.Actions.TalkAction.TalkSettings.EvaluateSimple(TinyLife.Actions.Action%2cTinyLife.Objects.PersonLike%2cSystem.Single%2cSystem.Single)" data-throw-if-not-resolved="false"></xref> and <xref href="TinyLife.Actions.TalkAction.TalkSettings.EvaluateFully(TinyLife.Actions.SocialAction)" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public delegate void TalkAction.TalkSettings.EvaluationResult(ActionInfo info, PersonLike partner, float originalGain, float originalRomancePercentage, float originalGoBadlyChance, ref float romanceGain, ref float friendshipGain, ref float romanceLoss, ref float friendshipLoss, ref float goBadlyChance)
    parameters:
    - id: info
      type: TinyLife.Actions.ActionInfo
      description: The action info that is being evaluated
    - id: partner
      type: TinyLife.Objects.PersonLike
      description: The partner of the action.
    - id: originalGain
      type: System.Single
      description: The amount of friendship and romance points that should be gained as a result of this action succeeding, without any default changes applied
    - id: originalRomancePercentage
      type: System.Single
      description: The amount of romance, out of <code class="paramref">originalGain</code> that should be gained as a result of this action succeeding, without any default changes applied
    - id: originalGoBadlyChance
      type: System.Single
      description: The chance, between 0 and 1, that the conversation should end badly. This value doesn't yet have any default changes applied.
    - id: romanceGain
      type: System.Single
      description: The amount of romance points that should be gained as a result of this action succeeding, which already has all default changes applied
    - id: friendshipGain
      type: System.Single
      description: The amount of friendship points that should be gained as a result of this action succeeding, which already has all default changes applied
    - id: romanceLoss
      type: System.Single
      description: The amount of romance points that should be lost as a result of this action going badly, which already has all default changes applied
    - id: friendshipLoss
      type: System.Single
      description: The amount of friendship points that should be lost as a result of this action going badly, which already has all default changes applied
    - id: goBadlyChance
      type: System.Single
      description: The chance, between 0 and 1, that the conversation should end badly. This value already has all of the default changes applied.
    content.vb: Public Delegate Sub TalkAction.TalkSettings.EvaluationResult(info As ActionInfo, partner As PersonLike, originalGain As Single, originalRomancePercentage As Single, originalGoBadlyChance As Single, romanceGain As Single, friendshipGain As Single, romanceLoss As Single, friendshipLoss As Single, goBadlyChance As Single)
  extensionMethods:
  - TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult.TinyLife.Utilities.Extensions.JsonCopy``1
references:
- uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluateSimple(TinyLife.Actions.Action,TinyLife.Objects.PersonLike,System.Single,System.Single)
  commentId: M:TinyLife.Actions.TalkAction.TalkSettings.EvaluateSimple(TinyLife.Actions.Action,TinyLife.Objects.PersonLike,System.Single,System.Single)
  isExternal: true
  href: TinyLife.Actions.TalkAction.TalkSettings.html#TinyLife_Actions_TalkAction_TalkSettings_EvaluateSimple_TinyLife_Actions_Action_TinyLife_Objects_PersonLike_System_Single_System_Single_
  name: EvaluateSimple(Action, PersonLike, float, float)
  nameWithType: TalkAction.TalkSettings.EvaluateSimple(Action, PersonLike, float, float)
  fullName: TinyLife.Actions.TalkAction.TalkSettings.EvaluateSimple(TinyLife.Actions.Action, TinyLife.Objects.PersonLike, float, float)
  nameWithType.vb: TalkAction.TalkSettings.EvaluateSimple(Action, PersonLike, Single, Single)
  fullName.vb: TinyLife.Actions.TalkAction.TalkSettings.EvaluateSimple(TinyLife.Actions.Action, TinyLife.Objects.PersonLike, Single, Single)
  name.vb: EvaluateSimple(Action, PersonLike, Single, Single)
  spec.csharp:
  - uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluateSimple(TinyLife.Actions.Action,TinyLife.Objects.PersonLike,System.Single,System.Single)
    name: EvaluateSimple
    href: TinyLife.Actions.TalkAction.TalkSettings.html#TinyLife_Actions_TalkAction_TalkSettings_EvaluateSimple_TinyLife_Actions_Action_TinyLife_Objects_PersonLike_System_Single_System_Single_
  - name: (
  - uid: TinyLife.Actions.Action
    name: Action
    href: TinyLife.Actions.Action.html
  - name: ','
  - name: " "
  - uid: TinyLife.Objects.PersonLike
    name: PersonLike
    href: TinyLife.Objects.PersonLike.html
  - name: ','
  - name: " "
  - uid: System.Single
    name: float
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.single
  - name: ','
  - name: " "
  - uid: System.Single
    name: float
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.single
  - name: )
  spec.vb:
  - uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluateSimple(TinyLife.Actions.Action,TinyLife.Objects.PersonLike,System.Single,System.Single)
    name: EvaluateSimple
    href: TinyLife.Actions.TalkAction.TalkSettings.html#TinyLife_Actions_TalkAction_TalkSettings_EvaluateSimple_TinyLife_Actions_Action_TinyLife_Objects_PersonLike_System_Single_System_Single_
  - name: (
  - uid: TinyLife.Actions.Action
    name: Action
    href: TinyLife.Actions.Action.html
  - name: ','
  - name: " "
  - uid: TinyLife.Objects.PersonLike
    name: PersonLike
    href: TinyLife.Objects.PersonLike.html
  - name: ','
  - name: " "
  - uid: System.Single
    name: Single
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.single
  - name: ','
  - name: " "
  - uid: System.Single
    name: Single
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.single
  - name: )
- uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluateFully(TinyLife.Actions.SocialAction)
  commentId: M:TinyLife.Actions.TalkAction.TalkSettings.EvaluateFully(TinyLife.Actions.SocialAction)
  href: TinyLife.Actions.TalkAction.TalkSettings.html#TinyLife_Actions_TalkAction_TalkSettings_EvaluateFully_TinyLife_Actions_SocialAction_
  name: EvaluateFully(SocialAction)
  nameWithType: TalkAction.TalkSettings.EvaluateFully(SocialAction)
  fullName: TinyLife.Actions.TalkAction.TalkSettings.EvaluateFully(TinyLife.Actions.SocialAction)
  spec.csharp:
  - uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluateFully(TinyLife.Actions.SocialAction)
    name: EvaluateFully
    href: TinyLife.Actions.TalkAction.TalkSettings.html#TinyLife_Actions_TalkAction_TalkSettings_EvaluateFully_TinyLife_Actions_SocialAction_
  - name: (
  - uid: TinyLife.Actions.SocialAction
    name: SocialAction
    href: TinyLife.Actions.SocialAction.html
  - name: )
  spec.vb:
  - uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluateFully(TinyLife.Actions.SocialAction)
    name: EvaluateFully
    href: TinyLife.Actions.TalkAction.TalkSettings.html#TinyLife_Actions_TalkAction_TalkSettings_EvaluateFully_TinyLife_Actions_SocialAction_
  - name: (
  - uid: TinyLife.Actions.SocialAction
    name: SocialAction
    href: TinyLife.Actions.SocialAction.html
  - name: )
- uid: TinyLife.Actions
  commentId: N:TinyLife.Actions
  href: TinyLife.html
  name: TinyLife.Actions
  nameWithType: TinyLife.Actions
  fullName: TinyLife.Actions
  spec.csharp:
  - uid: TinyLife
    name: TinyLife
    href: TinyLife.html
  - name: .
  - uid: TinyLife.Actions
    name: Actions
    href: TinyLife.Actions.html
  spec.vb:
  - uid: TinyLife
    name: TinyLife
    href: TinyLife.html
  - name: .
  - uid: TinyLife.Actions
    name: Actions
    href: TinyLife.Actions.html
- uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult.TinyLife.Utilities.Extensions.JsonCopy``1
  commentId: M:TinyLife.Utilities.Extensions.JsonCopy``1(``0)
  parent: TinyLife.Utilities.Extensions
  definition: TinyLife.Utilities.Extensions.JsonCopy``1(``0)
  href: TinyLife.Utilities.Extensions.html#TinyLife_Utilities_Extensions_JsonCopy__1___0_
  name: JsonCopy<EvaluationResult>(EvaluationResult)
  nameWithType: Extensions.JsonCopy<TalkAction.TalkSettings.EvaluationResult>(TalkAction.TalkSettings.EvaluationResult)
  fullName: TinyLife.Utilities.Extensions.JsonCopy<TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult>(TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult)
  nameWithType.vb: Extensions.JsonCopy(Of TalkAction.TalkSettings.EvaluationResult)(TalkAction.TalkSettings.EvaluationResult)
  fullName.vb: TinyLife.Utilities.Extensions.JsonCopy(Of TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult)(TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult)
  name.vb: JsonCopy(Of EvaluationResult)(EvaluationResult)
  spec.csharp:
  - uid: TinyLife.Utilities.Extensions.JsonCopy``1(TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult)
    name: JsonCopy
    href: TinyLife.Utilities.Extensions.html#TinyLife_Utilities_Extensions_JsonCopy__1___0_
  - name: <
  - uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
    name: EvaluationResult
    href: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult.html
  - name: '>'
  - name: (
  - uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
    name: EvaluationResult
    href: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult.html
  - name: )
  spec.vb:
  - uid: TinyLife.Utilities.Extensions.JsonCopy``1(TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult)
    name: JsonCopy
    href: TinyLife.Utilities.Extensions.html#TinyLife_Utilities_Extensions_JsonCopy__1___0_
  - name: (
  - name: Of
  - name: " "
  - uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
    name: EvaluationResult
    href: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult.html
  - name: )
  - name: (
  - uid: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult
    name: EvaluationResult
    href: TinyLife.Actions.TalkAction.TalkSettings.EvaluationResult.html
  - name: )
- uid: TinyLife.Actions.ActionInfo
  commentId: T:TinyLife.Actions.ActionInfo
  parent: TinyLife.Actions
  href: TinyLife.Actions.ActionInfo.html
  name: ActionInfo
  nameWithType: ActionInfo
  fullName: TinyLife.Actions.ActionInfo
- uid: TinyLife.Objects.PersonLike
  commentId: T:TinyLife.Objects.PersonLike
  parent: TinyLife.Objects
  href: TinyLife.Objects.PersonLike.html
  name: PersonLike
  nameWithType: PersonLike
  fullName: TinyLife.Objects.PersonLike
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: TinyLife.Utilities.Extensions.JsonCopy``1(``0)
  commentId: M:TinyLife.Utilities.Extensions.JsonCopy``1(``0)
  href: TinyLife.Utilities.Extensions.html#TinyLife_Utilities_Extensions_JsonCopy__1___0_
  name: JsonCopy<T>(T)
  nameWithType: Extensions.JsonCopy<T>(T)
  fullName: TinyLife.Utilities.Extensions.JsonCopy<T>(T)
  nameWithType.vb: Extensions.JsonCopy(Of T)(T)
  fullName.vb: TinyLife.Utilities.Extensions.JsonCopy(Of T)(T)
  name.vb: JsonCopy(Of T)(T)
  spec.csharp:
  - uid: TinyLife.Utilities.Extensions.JsonCopy``1(``0)
    name: JsonCopy
    href: TinyLife.Utilities.Extensions.html#TinyLife_Utilities_Extensions_JsonCopy__1___0_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: TinyLife.Utilities.Extensions.JsonCopy``1(``0)
    name: JsonCopy
    href: TinyLife.Utilities.Extensions.html#TinyLife_Utilities_Extensions_JsonCopy__1___0_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: TinyLife.Utilities.Extensions
  commentId: T:TinyLife.Utilities.Extensions
  parent: TinyLife.Utilities
  href: TinyLife.Utilities.Extensions.html
  name: Extensions
  nameWithType: Extensions
  fullName: TinyLife.Utilities.Extensions
- uid: TinyLife.Objects
  commentId: N:TinyLife.Objects
  href: TinyLife.html
  name: TinyLife.Objects
  nameWithType: TinyLife.Objects
  fullName: TinyLife.Objects
  spec.csharp:
  - uid: TinyLife
    name: TinyLife
    href: TinyLife.html
  - name: .
  - uid: TinyLife.Objects
    name: Objects
    href: TinyLife.Objects.html
  spec.vb:
  - uid: TinyLife
    name: TinyLife
    href: TinyLife.html
  - name: .
  - uid: TinyLife.Objects
    name: Objects
    href: TinyLife.Objects.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: TinyLife.Utilities
  commentId: N:TinyLife.Utilities
  href: TinyLife.html
  name: TinyLife.Utilities
  nameWithType: TinyLife.Utilities
  fullName: TinyLife.Utilities
  spec.csharp:
  - uid: TinyLife
    name: TinyLife
    href: TinyLife.html
  - name: .
  - uid: TinyLife.Utilities
    name: Utilities
    href: TinyLife.Utilities.html
  spec.vb:
  - uid: TinyLife
    name: TinyLife
    href: TinyLife.html
  - name: .
  - uid: TinyLife.Utilities
    name: Utilities
    href: TinyLife.Utilities.html
